name: openapi-validator

on:
  push:
    branches:
      - main  # Change this to the name of your main branch
  pull_request:
    branches:
      - main  # Change this to the name of your main branch

jobs:
  speccy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'validate openapi schema'
      uses: thiyagu06/openapi-validator-action@v1
      with:
        filepath: 'test-sample.json'
